# Colab設定

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [14]:
cd /content/drive/MyDrive/data

/content/drive/MyDrive/data


#使用套件載入

##資料處理用

In [15]:
import numpy as np
import pandas as pd

## 資料整理用

In [17]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

## 機器學習套件

In [67]:
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier      
from sklearn.ensemble import RandomForestClassifier  
from xgboost import XGBClassifier

#讀取訓練資料集



## 讀取train.csv

In [19]:
train_data=pd.read_csv('train.csv')
train_data.head()

yyyy  PerNo  PerStatus  sex  工作分類  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0  2014      1          0  1.0   1.0  ...     NaN     5.0  0.0   8.0  19138.0
1  2015      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
2  2016      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
3  2017      1          0  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
4  2014      3          0  0.0   1.0  ...     4.0     1.0  2.0   8.0   8181.0

[5 rows x 47 columns]

## 缺漏值處理

### 檢查有無缺漏值

In [20]:
train_data.isnull().sum()

yyyy            0
PerNo           0
PerStatus       0
sex            73
工作分類           73
職等             73
廠區代碼           73
管理層級           73
工作資歷1          73
工作資歷2          73
工作資歷3          73
工作資歷4          73
工作資歷5          73
專案時數           73
專案總數           73
當前專案角色         73
特殊專案佔比         73
工作地點           73
訓練時數A          73
訓練時數B          73
訓練時數C          73
生產總額           73
榮譽數            73
是否升遷           73
升遷速度           73
近三月請假數A        73
近一年請假數A        73
近三月請假數B        73
近一年請假數B        73
出差數A           73
出差數B           73
出差集中度          73
年度績效等級A        73
年度績效等級B        73
年度績效等級C        73
年齡層級           73
婚姻狀況           73
年資層級A          73
年資層級B          73
年資層級C          73
任職前工作平均年數      73
最高學歷         5326
畢業學校類別       3841
畢業科系類別         73
眷屬量            73
通勤成本           73
歸屬部門           73
dtype: int64

### 利用迴圈將缺漏值以平均值填入

In [21]:
for i in range(len(train_data.columns)):
  train_data[train_data.columns[i]].fillna(value=train_data[train_data.columns[i]].mean(),inplace=True)
train_data.isnull().sum()

yyyy         0
PerNo        0
PerStatus    0
sex          0
工作分類         0
職等           0
廠區代碼         0
管理層級         0
工作資歷1        0
工作資歷2        0
工作資歷3        0
工作資歷4        0
工作資歷5        0
專案時數         0
專案總數         0
當前專案角色       0
特殊專案佔比       0
工作地點         0
訓練時數A        0
訓練時數B        0
訓練時數C        0
生產總額         0
榮譽數          0
是否升遷         0
升遷速度         0
近三月請假數A      0
近一年請假數A      0
近三月請假數B      0
近一年請假數B      0
出差數A         0
出差數B         0
出差集中度        0
年度績效等級A      0
年度績效等級B      0
年度績效等級C      0
年齡層級         0
婚姻狀況         0
年資層級A        0
年資層級B        0
年資層級C        0
任職前工作平均年數    0
最高學歷         0
畢業學校類別       0
畢業科系類別       0
眷屬量          0
通勤成本         0
歸屬部門         0
dtype: int64

# 訓練資料分割與處理

## 設定y資料(訓練用預測目標)

In [22]:
y=train_data['PerStatus'].astype(int)
y.head()

0    0
1    0
2    0
3    0
4    0
Name: PerStatus, dtype: int64

## 設定X資料(訓練資料)

In [23]:
X=train_data.drop(['PerStatus','PerNo'],axis=1)
X.head()

yyyy  sex  工作分類   職等  廠區代碼  ...    畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0  2014  1.0   1.0  3.0  19.0  ...  3.491044     5.0  0.0   8.0  19138.0
1  2015  1.0   1.0  3.0  19.0  ...  3.491044     5.0  2.0   8.0  19138.0
2  2016  1.0   1.0  3.0  19.0  ...  3.491044     5.0  2.0   8.0  19138.0
3  2017  1.0   1.0  3.0  19.0  ...  3.491044     5.0  2.0   8.0  19138.0
4  2014  0.0   1.0  4.0   8.0  ...  4.000000     1.0  2.0   8.0   8181.0

[5 rows x 45 columns]

## 分割為訓練集與測試集

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X.iloc[:,:],y,test_size=0.3,random_state=0)
print('資料歸一化前:')
print(X_train)

資料歸一化前:
       yyyy  sex  工作分類   職等  廠區代碼  ...    畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
979    2016  0.0   1.0  7.0  14.0  ...  3.491044     8.0  1.0   8.0  14067.0
2265   2014  1.0   1.0  7.0  13.0  ...  3.491044     3.0  0.0   9.0  13065.0
12299  2015  0.0   1.0  7.0  14.0  ...  4.000000     2.0  1.0   8.0  14077.0
2363   2016  0.0   2.0  3.0  20.0  ...  5.000000     9.0  2.0   8.0  20127.0
5158   2015  1.0   1.0  4.0   8.0  ...  4.000000     8.0  1.0   8.0   8162.0
...     ...  ...   ...  ...   ...  ...       ...     ...  ...   ...      ...
13123  2017  0.0   1.0  3.0  17.0  ...  1.000000     9.0  2.0   8.0  17068.0
3264   2014  0.0   1.0  3.0  10.0  ...  3.000000     8.0  2.0   8.0  10005.0
9845   2017  1.0   1.0  4.0  19.0  ...  3.491044     8.0  1.0   8.0  19043.0
10799  2015  0.0   2.0  4.0  14.0  ...  3.000000     1.0  0.0   8.0  14195.0
2732   2017  1.0   1.0  3.0  19.0  ...  3.000000     6.0  2.0   8.0  19039.0

[10074 rows x 45 columns]


### 資料歸一化

In [25]:
ss=MinMaxScaler()                          
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)
print('資料歸一化後:')
print(X_train)

資料歸一化後:
[[0.66666667 0.         0.         ... 0.33333333 0.33333333 0.66219264]
 [0.         1.         0.         ... 0.         0.41666667 0.6070741 ]
 [0.33333333 0.         0.         ... 0.33333333 0.33333333 0.66274273]
 ...
 [1.         1.         0.         ... 0.33333333 0.33333333 0.93591507]
 [0.33333333 0.         1.         ... 0.         0.33333333 0.66923373]
 [1.         1.         0.         ... 0.66666667 0.33333333 0.93569503]]


# 機器學習與預測

## 機器學習

In [46]:
model=SGDClassifier()
model.fit(X_train,y_train)
print(f'訓練分數:{model.score(X_test,y_test)}')

訓練分數:0.943260768874479


## 預測資料前處理

### 讀取test.csv

In [27]:
test_data=pd.read_csv('test.csv')
test_data.head()

yyyy  PerNo  PerStatus  sex  工作分類  ...  畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0  2018      1        NaN  1.0   1.0  ...     NaN     5.0  2.0   8.0  19138.0
1  2018      3        NaN  0.0   1.0  ...     4.0     1.0  2.0   8.0   8181.0
2  2018      7        NaN  0.0   1.0  ...     NaN     5.0  0.0  10.0   4010.0
3  2018     15        NaN  0.0   1.0  ...     4.0     8.0  2.0   9.0   2177.0
4  2018     16        NaN  0.0   1.0  ...     3.0     3.0  2.0  10.0  12072.0

[5 rows x 47 columns]

### 缺漏值檢查與填入

In [28]:
test_data.isnull().sum()

yyyy            0
PerNo           0
PerStatus    3739
sex            18
工作分類           18
職等             18
廠區代碼           18
管理層級           18
工作資歷1          18
工作資歷2          18
工作資歷3          18
工作資歷4          18
工作資歷5          18
專案時數           18
專案總數           18
當前專案角色         18
特殊專案佔比         18
工作地點           18
訓練時數A          18
訓練時數B          18
訓練時數C          18
生產總額           18
榮譽數            18
是否升遷           18
升遷速度           18
近三月請假數A        18
近一年請假數A        18
近三月請假數B        18
近一年請假數B        18
出差數A           18
出差數B           18
出差集中度          18
年度績效等級A        18
年度績效等級B        18
年度績效等級C        18
年齡層級           18
婚姻狀況           18
年資層級A          18
年資層級B          18
年資層級C          18
任職前工作平均年數      18
最高學歷         1384
畢業學校類別       1067
畢業科系類別         18
眷屬量            18
通勤成本           18
歸屬部門           18
dtype: int64

In [29]:
for i in range(len(test_data.columns)):
  test_data[test_data.columns[i]].fillna(value=test_data[test_data.columns[i]].mean(),inplace=True)
test_data.isnull().sum()

yyyy            0
PerNo           0
PerStatus    3739
sex             0
工作分類            0
職等              0
廠區代碼            0
管理層級            0
工作資歷1           0
工作資歷2           0
工作資歷3           0
工作資歷4           0
工作資歷5           0
專案時數            0
專案總數            0
當前專案角色          0
特殊專案佔比          0
工作地點            0
訓練時數A           0
訓練時數B           0
訓練時數C           0
生產總額            0
榮譽數             0
是否升遷            0
升遷速度            0
近三月請假數A         0
近一年請假數A         0
近三月請假數B         0
近一年請假數B         0
出差數A            0
出差數B            0
出差集中度           0
年度績效等級A         0
年度績效等級B         0
年度績效等級C         0
年齡層級            0
婚姻狀況            0
年資層級A           0
年資層級B           0
年資層級C           0
任職前工作平均年數       0
最高學歷            0
畢業學校類別          0
畢業科系類別          0
眷屬量             0
通勤成本            0
歸屬部門            0
dtype: int64

### 預測資料處理


In [71]:
test_X=test_data.drop(['PerStatus','PerNo'],axis=1)
test_X

yyyy  sex  工作分類   職等  廠區代碼  ...    畢業學校類別  畢業科系類別  眷屬量  通勤成本     歸屬部門
0     2018  1.0   1.0  3.0  19.0  ...  3.504865     5.0  2.0   8.0  19138.0
1     2018  0.0   1.0  4.0   8.0  ...  4.000000     1.0  2.0   8.0   8181.0
2     2018  0.0   1.0  4.0   4.0  ...  3.504865     5.0  0.0  10.0   4010.0
3     2018  0.0   1.0  4.0   2.0  ...  4.000000     8.0  2.0   9.0   2177.0
4     2018  0.0   1.0  4.0  12.0  ...  3.000000     3.0  2.0  10.0  12072.0
...    ...  ...   ...  ...   ...  ...       ...     ...  ...   ...      ...
3734  2018  1.0   1.0  7.0  20.0  ...  3.504865     5.0  0.0   8.0  20123.0
3735  2018  0.0   1.0  4.0  14.0  ...  3.000000     7.0  1.0   8.0  14053.0
3736  2018  1.0   1.0  4.0  13.0  ...  4.000000     7.0  0.0   8.0  13084.0
3737  2018  1.0   1.0  7.0   8.0  ...  3.000000     8.0  2.0   8.0   8012.0
3738  2018  1.0   2.0  2.0   8.0  ...  3.000000     8.0  0.0   9.0   8206.0

[3739 rows x 45 columns]

##預測

In [47]:
y_pred=model.predict(test_X)
y_pred

array([1, 0, 0, ..., 1, 0, 0])

#預測結果輸出

In [48]:
No=pd.read_csv('test.csv')
ans={'PerNo':No['PerNo'],'PerStatus':y_pred}

In [49]:
data_F=pd.DataFrame(ans)

data_F.to_csv('SGDClassifier.csv', index=False)

# 其他模型預測

## 決策樹

In [54]:
model_DT=DecisionTreeClassifier()
model_DT.fit(X_train,y_train)
print(f'訓練分數:{model_DT.score(X_test,y_test)}')
y_pred=model_DT.predict(test_X)
y_pred

訓練分數:0.8946271421954609


array([1, 0, 0, ..., 0, 1, 1])

## 隨機叢林

In [76]:
model_rfc=RandomForestClassifier()
model_rfc.fit(X_train,y_train)
print(f'訓練分數:{model_rfc.score(X_test,y_test)}')
y_pred=model_rfc.predict(test_X)
y_pred

訓練分數:0.943260768874479


array([0, 0, 0, ..., 0, 0, 0])

## xgboost

In [89]:
model_xgb=XGBClassifier()
model_xgb.fit(X_train,y_train)
print(f'訓練分數:{model_xgb.score(X_test,y_test)}')
test_X=ss.fit_transform(test_X)
y_pred=model_xgb.predict(test_X)
y_pred

訓練分數:0.943723946271422


array([0, 0, 0, ..., 0, 0, 0])

RFC 0.943 0.1083333

DT 0.858  0.1358208

SGD 0.943 0.1517678

XGB 0.943 0.065
